controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
kernel: 
    resource: ../src/Kernel.php
    type: annotation
api_loginçcheck: 
    path: /api/login_check
api.swigger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }